[package]
name = "extrema_infra"
version = "0.1.0"
edition = "2024"

[lib]
name = "extrema_infra"
path = "src/lib.rs"

[dependencies]
# Networking & async
tokio = { version = "1.48.0", features = ["full"] }
reqwest = { version = "0.12.24", features = ["json", "gzip"] }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
tungstenite = "0.28.0"
futures = "0.3.31"
futures-util = "0.3.31"
zeromq = "0.4.1"

# Data & Feature processing
polars = { version = "0.52.0", default-features = false }

# Parsing & Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
simd-json = "0.17.0"

# Cryptography & Encoding
hmac = "0.12.1"
sha2 = "0.10.9"
rmp-serde = "1.3.0"
data-encoding = "2.9.0"

# Logging & Tracing
tracing = "0.1.43"
tracing-subscriber = "0.3.22"

# Environment & Error handling
dotenv = "0.15.0"
thiserror = "2.0.17"

[features]
default = []

cex_clients = [
    "binance_cm",
    "binance_um",
    "okx",
]
binance_cm = []
binance_um = []
okx = []